name : 'my pipeline'

on:
  workflow_dispatch:

jobs:
  terraform:
    name: terraform
    runs-on: ubuntu-latest

    defauts:
      run:
        shell: bash
        working-directory: test


    strategy:
     max-parallel: 1
     matrix:
       environment: [test]
        include:
        - environment: test
          secret_name: TEST_PASSWORD
    

    steps: 
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terrafrom
        uses: hashicorp/setup-terrform@v1
      
      - name: Setup GCP Credentials
        uses: google-github-actions/setup-gcloud@v0
        with: 
          service_account_key: ${{ secrets[matrix.secret_name] }}
          export_default_credentials: true
      
      - name: terrafrom diff
        id: diff
        run: terraform fmr diff -write=true

      - name: terraform fmt
        id: fmt
        run: terraform fmt - check

      - name: Terraform init
        run: terraform init -backend-config vars/${{ matrix.environment }}-backend.tfvars -reconfigure

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -out=$ {{ github.sha }}.plan

      - name: Terrafrom Apply
        run: terrafrom apply -auto-approve "{{ github.sha}}.plan"